apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv
spec:
  capacity:
    storage: 20M
  accessModes:
    # RW once is ok since minikube is is a single node cluster
    - ReadWriteOnce
  hostPath:
    path: /data/webapp-volume

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20M